/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.table.JTableHeader;
/**
 *
 * @author USER
 */
public class CRUDSanciones extends javax.swing.JFrame {
Connection conn;
Statement sent;
String fecha;
DefaultTableModel model;
    /**
     * Creates new form CRUDSanciones
     */
    public CRUDSanciones() {
        initComponents();
        opa.setOpaque(true);
        opa.setBackground(new Color(74,74,82, 200));
        setLocationRelativeTo(null);
        fecha();
        Llenar();
    }
void fecha(){
        LocalDateTime hoy = LocalDateTime.now();
        int dia = hoy.getDayOfMonth();
        int mes = hoy.getMonthValue();
        int anio = hoy.getYear();
        fecha= dia+"-"+mes+"-"+anio;
        lblfecha.setText(fecha);
    }
void Nueva(){
    try{
            conn = DB.Mysql.getConnection();
            String sql = "insert into SANCIONES (ID_MIEMBRO,FECHA_SANCION,TIPO_SANCION,DURA_SANCION)"
                    +"values("
                    +"'"+lblMiembro.getText()+"',"
                    +"'"+fecha+"',"
                    +"'"+cmbTipoSan.getSelectedItem().toString()+"',"
                    +"'"+cmbTipoSan1.getSelectedItem().toString()+"')";
            sent = conn.createStatement();
            int n = sent.executeUpdate(sql);
            if(n>0){
                JOptionPane.showMessageDialog(null,"Datos guardados");
                Limpiar();
            }else{
                JOptionPane.showMessageDialog(null,"No se pudieron guardar los datos");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        Llenar();
        Limpiar();
}
void Limpiar(){
    txtMiembro.setText("");
    lblMiembro.setText("");
    cmbTipoSan1.setSelectedItem(1);
    cmbTipoSan.setSelectedItem(1);
}
void Llenar(){
    JTableHeader header = tblDB.getTableHeader();
        Font headerFont = new Font("Dialog", Font.BOLD, 12); 
        header.setFont(headerFont);
        header.setBackground(new Color(51, 51, 55));
        header.setForeground(Color.white);
        try {
            conn = DB.Mysql.getConnection();
            String[] titulos ={"ID","MIEMBRO","FECHA","TIPO","DURACIÓN"};
            String sql = "Select * from Sanciones";
            model = new DefaultTableModel(null, titulos);
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            String[] fila = new String[5];
            while (rs.next()){
                fila[0]=rs.getString("ID_SANCION");
                fila[1]=rs.getString("ID_MIEMBRO");
                fila[2]=rs.getString("FECHA_SANCION");
                fila[3]=rs.getString("TIPO_SANCION");
                fila[4]=rs.getString("DURA_SANCION");
                model.addRow(fila);
            }
            tblDB.setModel(model);
            
        } catch (Exception e){
            e.printStackTrace();
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblNombreMiembroSan = new javax.swing.JLabel();
        lblMiembroSan = new javax.swing.JLabel();
        lblTipoSan = new javax.swing.JLabel();
        cmbTipoSan = new javax.swing.JComboBox<>();
        lblFechaSan = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDB = new javax.swing.JTable();
        txtMiembro = new javax.swing.JTextField();
        lblfecha = new javax.swing.JLabel();
        lblMiembro = new javax.swing.JLabel();
        lblbuscar = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lblMiembroSan1 = new javax.swing.JLabel();
        cmbTipoSan1 = new javax.swing.JComboBox<>();
        opa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreMiembroSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombreMiembroSan.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreMiembroSan.setText("Nombre del miembro:");
        jPanel1.add(lblNombreMiembroSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lblMiembroSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMiembroSan.setForeground(new java.awt.Color(255, 255, 255));
        lblMiembroSan.setText("ID del miembro:");
        jPanel1.add(lblMiembroSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblTipoSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTipoSan.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoSan.setText("Tipo de Sanción:");
        jPanel1.add(lblTipoSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        cmbTipoSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbTipoSan.setForeground(new java.awt.Color(255, 255, 255));
        cmbTipoSan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la duracion", "1 dia", "8 dias", "15 dias", "1 mes", "6 meses", "1 año", "Permanente" }));
        jPanel1.add(cmbTipoSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 150, 22));

        lblFechaSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFechaSan.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaSan.setText("Fecha de Sanción:");
        jPanel1.add(lblFechaSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblTitulo.setBackground(new java.awt.Color(51, 102, 0));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestión de Sanciones");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        tblDB.setBackground(new java.awt.Color(32, 32, 53));
        tblDB.setBorder(new javax.swing.border.MatteBorder(null));
        tblDB.setForeground(new java.awt.Color(255, 255, 255));
        tblDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDB);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 330, 280));

        txtMiembro.setBackground(new java.awt.Color(32, 32, 53));
        txtMiembro.setForeground(new java.awt.Color(255, 255, 255));
        txtMiembro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMiembro.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMiembro.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtMiembro.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtMiembro.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 22));

        lblfecha.setBackground(new java.awt.Color(204, 204, 204));
        lblfecha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        jPanel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 22));

        lblMiembro.setBackground(new java.awt.Color(204, 204, 204));
        lblMiembro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblMiembro.setForeground(new java.awt.Color(255, 255, 255));
        lblMiembro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        jPanel1.add(lblMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 22));

        lblbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descargar.png"))); // NOI18N
        lblbuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbuscarMouseClicked(evt);
            }
        });
        jPanel1.add(lblbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        btnnuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnnuevo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Generar");
        btnnuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 96, 37));

        btnsalir.setBackground(new java.awt.Color(0, 0, 0));
        btnsalir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Volver");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 96, 37));

        lblMiembroSan1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMiembroSan1.setForeground(new java.awt.Color(255, 255, 255));
        lblMiembroSan1.setText("Duración:");
        jPanel1.add(lblMiembroSan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cmbTipoSan1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbTipoSan1.setForeground(new java.awt.Color(255, 255, 255));
        cmbTipoSan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el motivo", "Libro extraviado", "Libro dañado", "Perdida total del libro", "Entregado fuera de tiempo" }));
        jPanel1.add(cmbTipoSan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 150, 22));
        jPanel1.add(opa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mainbiblio2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbuscarMouseClicked
        // TODO add your handling code here:
        try{
            conn = DB.Mysql.getConnection();
            String sql = "Select NOMBRE_MIEMBRO from Miembros where ID_MIEMBRO='" + txtMiembro.getText()+"'";
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
            String a = rs.getString(1);
            if(rs!=null){
                //JOptionPane.showMessageDialog(null, "Registro encontrado con éxito");
                lblMiembro.setText(rs.getString(1));

            }else{
                JOptionPane.showMessageDialog(null, "Error");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Registro no encontrado");
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblbuscarMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        String com = "Seleccione el motivo";
        String con = "Seleccione la duracion";
        if(txtMiembro.getText().equals("") || cmbTipoSan.getSelectedItem().equals(com) || cmbTipoSan1.getSelectedItem().equals(con)){
            JOptionPane.showMessageDialog(null, "Por favor llene lo necesario");
        }else{
            Nueva();
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        if(biblio.Login.rang.equals("0")){
            new MenuAdmin().setVisible(true);
            this.setVisible(false);
        }if(biblio.Login.rang.equals("1")){
            new MenuEncargado().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDSanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDSanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDSanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDSanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDSanciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbTipoSan;
    private javax.swing.JComboBox<String> cmbTipoSan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFechaSan;
    private javax.swing.JLabel lblMiembro;
    private javax.swing.JLabel lblMiembroSan;
    private javax.swing.JLabel lblMiembroSan1;
    private javax.swing.JLabel lblNombreMiembroSan;
    private javax.swing.JLabel lblTipoSan;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblbuscar;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel opa;
    private javax.swing.JTable tblDB;
    private javax.swing.JTextField txtMiembro;
    // End of variables declaration//GEN-END:variables
}
