package biblio;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author POO
 */

import java.awt.Color;
import java.sql.SQLException;
import java.sql.Connection;
import org.mindrot.jbcrypt.BCrypt;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {
    public static Connection Conn;
    public static String rang="";
    Statement sent;
public static String users="0";

    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        opa.setOpaque(true);
        opa.setBackground(new Color(74,74,82, 200));
        setLocationRelativeTo(null);
    }
    void Limpiar(){
        txtusuario.setText("");
        password.setText("");
    }
    void Rango(){
        String sql ="SELECT RANGO_USUARIO from USUARIO WHERE NOMBRE_USUARIO='"+txtusuario.getText()+"'";
        try{
            Conn = DB.Mysql.getConnection();
            sent = Conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
            rang= rs.getString(1);
    }catch (SQLException e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnacceder = new javax.swing.JButton();
        btnsalirlogin = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        opa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        password.setBackground(new java.awt.Color(32, 32, 53));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.setCaretColor(new java.awt.Color(255, 255, 255));
        password.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de Sesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 12, -1, -1));

        btnacceder.setBackground(new java.awt.Color(18, 18, 18));
        btnacceder.setForeground(new java.awt.Color(255, 255, 255));
        btnacceder.setText("Acceder");
        btnacceder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnacceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccederActionPerformed(evt);
            }
        });
        jPanel2.add(btnacceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 280, 80, 30));

        btnsalirlogin.setBackground(new java.awt.Color(18, 18, 18));
        btnsalirlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnsalirlogin.setText("Volver");
        btnsalirlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalirlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalirlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 80, 30));

        txtusuario.setBackground(new java.awt.Color(32, 32, 53));
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtusuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusuario.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtusuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 126, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¿Olvidaste tu contraseña?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("Haz click aquí");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        lbluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blackuser-removebg-preview.png"))); // NOI18N
        jPanel2.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        opa.setBackground(new java.awt.Color(51, 51, 255));
        opa.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(opa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 350));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 300, 350));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/library-7720589_960_720.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccederActionPerformed
        // TODO add your handling code here
        String usuario=txtusuario.getText();
        String pass=password.getText();
        String pass1="";
        String sql ="SELECT CONTRASENIA_USUARIO from USUARIO WHERE NOMBRE_USUARIO='"+usuario+"'";
        if(password.getText().equals("") || txtusuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Inserte su usuario y contraseña", "ALERTA", HEIGHT);
            
        }else{
        try{

            Conn = DB.Mysql.getConnection();
            sent = Conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
            pass1= rs.getString(1);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null,"Usuario no encontrado");
            Limpiar();
        }
    if(BCrypt.checkpw(pass, pass1)){
        JOptionPane.showMessageDialog(null, "Login exitoso");
        Rango();
        if(rang.equals("0")){
            new MenuAdmin().setVisible(true);
            this.setVisible(false);
        }if(rang.equals("1")){
        new MenuEncargado().setVisible(true);
        this.setVisible(false);
        }
    }else{
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
            Limpiar();
        }
        }
    }//GEN-LAST:event_btnaccederActionPerformed

    private void btnsalirloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirloginActionPerformed
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirloginActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Función en desarrollo");
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacceder;
    private javax.swing.JButton btnsalirlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel opa;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
