/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;

import javax.swing.SwingConstants;

/**
 *
 * @author Juan Soto
 */
public class MenuEncargado extends javax.swing.JFrame {

    /**
     * Creates new form MenuEncargado
     */
    public MenuEncargado() {
        initComponents(); 
        setLocationRelativeTo(null);
        lblTitulo.setText("Bienvenid@, "+Login.nom);
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnmiembros = new javax.swing.JButton();
        btnrecepcion = new javax.swing.JButton();
        btnprestamos = new javax.swing.JButton();
        btnhistorial = new javax.swing.JButton();
        btnsancion = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(74, 74, 82));

        btnmiembros.setBackground(new java.awt.Color(0, 0, 0));
        btnmiembros.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnmiembros.setForeground(new java.awt.Color(255, 255, 255));
        btnmiembros.setText("Miembros");
        btnmiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmiembrosActionPerformed(evt);
            }
        });

        btnrecepcion.setBackground(new java.awt.Color(0, 0, 0));
        btnrecepcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnrecepcion.setForeground(new java.awt.Color(255, 255, 255));
        btnrecepcion.setText("Recepciones");
        btnrecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecepcionActionPerformed(evt);
            }
        });

        btnprestamos.setBackground(new java.awt.Color(0, 0, 0));
        btnprestamos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnprestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnprestamos.setText("Préstamos");
        btnprestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamosActionPerformed(evt);
            }
        });

        btnhistorial.setBackground(new java.awt.Color(0, 0, 0));
        btnhistorial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnhistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnhistorial.setText("Historial");
        btnhistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistorialActionPerformed(evt);
            }
        });

        btnsancion.setBackground(new java.awt.Color(0, 0, 0));
        btnsancion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnsancion.setForeground(new java.awt.Color(255, 255, 255));
        btnsancion.setText("Sanciones");
        btnsancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsancionActionPerformed(evt);
            }
        });

        lblTitulo.setBackground(new java.awt.Color(51, 102, 0));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Bienvenido, ");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Cerrar Sesión");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsancion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnmiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnprestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnrecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsancion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamosActionPerformed
        // TODO add your handling code here:
        new Prestamos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnprestamosActionPerformed

    private void btnmiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmiembrosActionPerformed
        // TODO add your handling code here:
        new CRUDMiembros().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmiembrosActionPerformed

    private void btnsancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsancionActionPerformed
        // TODO add your handling code here:
        new CRUDSanciones().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnsancionActionPerformed

    private void btnhistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistorialActionPerformed
        // TODO add your handling code here:
        new Historial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnhistorialActionPerformed

    private void btnrecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecepcionActionPerformed
        // TODO add your handling code here:
        new Recepciones().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnrecepcionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEncargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhistorial;
    private javax.swing.JButton btnmiembros;
    private javax.swing.JButton btnprestamos;
    private javax.swing.JButton btnrecepcion;
    private javax.swing.JButton btnsancion;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
