/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;

/**
 *
 * @author Juan Soto
 */
public class MenuEncargado extends javax.swing.JFrame {

    /**
     * Creates new form MenuEncargado
     */
    public MenuEncargado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmiembros = new javax.swing.JButton();
        btnrecepcion = new javax.swing.JButton();
        btnprestamos = new javax.swing.JButton();
        btnhistorial = new javax.swing.JButton();
        btnsancion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnmiembros.setText("Miembros");
        btnmiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmiembrosActionPerformed(evt);
            }
        });

        btnrecepcion.setText("Recepciones");
        btnrecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecepcionActionPerformed(evt);
            }
        });

        btnprestamos.setText("Préstamos");
        btnprestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamosActionPerformed(evt);
            }
        });

        btnhistorial.setText("Historial");
        btnhistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistorialActionPerformed(evt);
            }
        });

        btnsancion.setText("Sanciones");
        btnsancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhistorial)
                    .addComponent(btnprestamos)
                    .addComponent(btnmiembros)
                    .addComponent(btnrecepcion)
                    .addComponent(btnsancion))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmiembros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnprestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrecepcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhistorial)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamosActionPerformed
        // TODO add your handling code here:
        new Prestamos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnprestamosActionPerformed

    private void btnmiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmiembrosActionPerformed
        // TODO add your handling code here:
        new CRUDMiembros().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmiembrosActionPerformed

    private void btnsancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsancionActionPerformed
        // TODO add your handling code here:
        new CRUDSanciones().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnsancionActionPerformed

    private void btnhistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistorialActionPerformed
        // TODO add your handling code here:
        new Historial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnhistorialActionPerformed

    private void btnrecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecepcionActionPerformed
        // TODO add your handling code here:
        new Recepciones().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnrecepcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEncargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhistorial;
    private javax.swing.JButton btnmiembros;
    private javax.swing.JButton btnprestamos;
    private javax.swing.JButton btnrecepcion;
    private javax.swing.JButton btnsancion;
    // End of variables declaration//GEN-END:variables
}
