/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Soto
 */
public class Recepciones extends javax.swing.JFrame {
Connection conn;
Statement sent;
String fecha;
String ide="";
    /**
     * Creates new form rere
     */
    public Recepciones() {
        initComponents();
        setLocationRelativeTo(null);
        fecha();
        opa.setOpaque(true);
        opa.setBackground(new Color(74,74,82, 200));
    }
void Limpiar(){
    txtIDMiembro.setText("");
    txtIDMiembro.setText("");
    lblMiembro.setText("");
    lblLibro.setText("");
}
void fecha(){
        LocalDateTime hoy = LocalDateTime.now();
        int dia = hoy.getDayOfMonth();
        int mes = hoy.getMonthValue();
        int anio = hoy.getYear();
        fecha= dia+"-"+mes+"-"+anio;
        lblfecha.setText(fecha);
    }
void Nueva(){
        try{
            conn = DB.Mysql.getConnection();
            String sql = "insert into Recepciones (ID_LIBRO,ID_PRESTAMO,FECHA_DEVOLUCION)"
                    +"values("
                    +"'"+txtIDLibro.getText()+"',"
                    +"'"+ide+"',"
                    +"'"+fecha+"')";
            sent = conn.createStatement();
            int n = sent.executeUpdate(sql);
            if(n>0){
                JOptionPane.showMessageDialog(null,"Datos guardados");
                Limpiar();
            }else{
                JOptionPane.showMessageDialog(null,"No se pudieron guardar los datos");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        Limpiar();
}
void iden(){
    try{
            conn = DB.Mysql.getConnection();
            String sql = "Select ID_PRESTAMO from Prestamos where ID_LIBRO='" +txtIDLibro.getText() +"' AND ID_MIEMBRO='"+txtIDMiembro.getText()+"'";
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
            ide = rs.getString(1);
            if(rs!=null){
                //JOptionPane.showMessageDialog(null, "Registro encontrado con éxito");

            }else{
                JOptionPane.showMessageDialog(null, "Error");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Registro no encontrado");
            e.printStackTrace();
        }
    Limpiar();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIDMiembroRecep = new javax.swing.JLabel();
        lblNombreMiembroRecep = new javax.swing.JLabel();
        lblIDLibroRecep = new javax.swing.JLabel();
        lblNombreLibroRecep = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDLibro = new javax.swing.JTextField();
        lblLibro = new javax.swing.JLabel();
        txtIDMiembro = new javax.swing.JTextField();
        lblfecha = new javax.swing.JLabel();
        lblMiembro = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        lblbuscar2 = new javax.swing.JLabel();
        lblbuscar1 = new javax.swing.JLabel();
        opa = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIDMiembroRecep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIDMiembroRecep.setForeground(new java.awt.Color(255, 255, 255));
        lblIDMiembroRecep.setText("ID del miembro:");
        jPanel1.add(lblIDMiembroRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblNombreMiembroRecep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombreMiembroRecep.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreMiembroRecep.setText("Nombre del Miembro:");
        jPanel1.add(lblNombreMiembroRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        lblIDLibroRecep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIDLibroRecep.setForeground(new java.awt.Color(255, 255, 255));
        lblIDLibroRecep.setText("ID del libro:");
        jPanel1.add(lblIDLibroRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblNombreLibroRecep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombreLibroRecep.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreLibroRecep.setText("Nombre del libro:");
        jPanel1.add(lblNombreLibroRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de recepción:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtIDLibro.setBackground(new java.awt.Color(32, 32, 53));
        txtIDLibro.setForeground(new java.awt.Color(255, 255, 255));
        txtIDLibro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIDLibro.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIDLibro.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtIDLibro.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtIDLibro.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtIDLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 22));

        lblLibro.setBackground(new java.awt.Color(204, 204, 204));
        lblLibro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblLibro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        jPanel1.add(lblLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, 22));

        txtIDMiembro.setBackground(new java.awt.Color(32, 32, 53));
        txtIDMiembro.setForeground(new java.awt.Color(255, 255, 255));
        txtIDMiembro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIDMiembro.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIDMiembro.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtIDMiembro.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtIDMiembro.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtIDMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 22));

        lblfecha.setBackground(new java.awt.Color(204, 204, 204));
        lblfecha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        jPanel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 22));

        lblMiembro.setBackground(new java.awt.Color(204, 204, 204));
        lblMiembro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblMiembro.setForeground(new java.awt.Color(255, 255, 255));
        lblMiembro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        jPanel1.add(lblMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 150, 22));

        btnsalir.setBackground(new java.awt.Color(0, 0, 0));
        btnsalir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Volver");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 96, 37));

        btnnuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnnuevo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Registrar");
        btnnuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 96, 37));

        lblbuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descargar.png"))); // NOI18N
        lblbuscar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblbuscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbuscar2MouseClicked(evt);
            }
        });
        jPanel1.add(lblbuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        lblbuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descargar.png"))); // NOI18N
        lblbuscar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblbuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbuscar1MouseClicked(evt);
            }
        });
        jPanel1.add(lblbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
        jPanel1.add(opa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 390, 270));

        lblTitulo.setBackground(new java.awt.Color(51, 102, 0));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Recepción de libros");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mainbiblio2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        if(biblio.Login.rang.equals("0")){
            new MenuAdmin().setVisible(true);
            this.setVisible(false);
        }if(biblio.Login.rang.equals("1")){
            new MenuEncargado().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        if(txtIDLibro.getText().equals("") || txtIDMiembro.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
        }else{
            iden();
            Nueva();
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void lblbuscar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbuscar2MouseClicked
        String idMiembro = txtIDMiembro.getText();

        if (idMiembro.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa el ID del miembro.");
            return;
        }

        try (Connection con = DB.Mysql.getConnection()){
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT NOMBRE_MIEMBRO FROM Miembros WHERE ID_MIEMBRO = ?");
            ps.setString(1, idMiembro);

            try (ResultSet rs = ps.executeQuery()) {

                if (rs.next()) {
                    lblMiembro.setText(rs.getString("NOMBRE_MIEMBRO"));
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró un miembro con ese ID.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el miembro: " + e.getMessage());
        }
    }//GEN-LAST:event_lblbuscar2MouseClicked

    private void lblbuscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbuscar1MouseClicked
        // TODO add your handling code here:
        String idLibro = txtIDLibro.getText(); // Obtener el ID del libro ingresado

        if (idLibro.isEmpty()) { // Validar si el campo está vacío
            JOptionPane.showMessageDialog(this, "Por favor, ingresa el ID del libro.");
            return;
        }

        try (Connection con = DB.Mysql.getConnection()){ // Establecer conexión a la BD
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT TITULO_LIBRO FROM libros WHERE ID_LIBRO = ?");  // Ajustar
            ps.setString(1, idLibro); // Asignar el ID del libro al parámetro

            try (ResultSet rs = ps.executeQuery()) { // Ejecutar la consulta

                if (rs.next()) { // Si se encuentra el libro
                    lblLibro.setText(rs.getString("TITULO_LIBRO")); // Agregar el título al ComboBox
                } else { // Si no se encuentra el libro
                    JOptionPane.showMessageDialog(this, "No se encontró un libro con ese ID.");
                }
            }
        } catch (Exception e) { // Manejar errores
            JOptionPane.showMessageDialog(this, "Error al buscar el libro: " + e.getMessage());
        }
    }//GEN-LAST:event_lblbuscar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIDLibroRecep;
    private javax.swing.JLabel lblIDMiembroRecep;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblMiembro;
    private javax.swing.JLabel lblNombreLibroRecep;
    private javax.swing.JLabel lblNombreMiembroRecep;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblbuscar1;
    private javax.swing.JLabel lblbuscar2;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel opa;
    private javax.swing.JTextField txtIDLibro;
    private javax.swing.JTextField txtIDMiembro;
    // End of variables declaration//GEN-END:variables
}
