/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Juan Soto
 */
public class usuarios extends javax.swing.JFrame {
Connection conn;
Statement sent;
Integer jrb=0;
String usuario="a";
String hashpass="";
String validar="f";
    /**
     * Creates new form usuarios
     */
    public usuarios() {
        initComponents();
        opa.setOpaque(true);
        opa.setBackground(new Color(74,74,82, 200));
        setLocationRelativeTo(null);
    }
    
    void hash(){
         String contraplano = pass1.getText();
         hashpass = BCrypt.hashpw(contraplano, BCrypt.gensalt());
    }
    
void ver(){
    
    String sql="Select NOMBRE_USUARIO from USUARIO where NOMBRE_USUARIO='"+txtusuario.getText()+"'";
    try{

            conn = DB.Mysql.getConnection();
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
            usuario = rs.getString(1);
        }catch (Exception e){
            //JOptionPane.showMessageDialog(null,e.getMessage());
        }
}

void verf(){
    validar="t";
    Integer a=pass1.getText().length();
    Integer b=pass2.getText().length();
    if(usuario.equals(txtusuario.getText())){
            JOptionPane.showMessageDialog(null, "Usuario no válido, ya se usó en otro registro");
            validar="f";
        }if(pass1.getText().equals("") || txtusuario.getText().equals("") || pass2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
            validar="f";
        }if(!pass1.getText().equals(pass2.getText())){
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden, intentelo de nuevo");
            validar="f";
        }if(a<8 || b<8){
            JOptionPane.showMessageDialog(null, "La contraseña debe contener por lo menos 8 carácteres");
            validar="f";
        }
}
void jrbrango(){
    if(jrbencargado.isSelected()){
        jrb=1;
    }if(jrbadmin.isSelected()){
        jrb=0;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        pass1 = new javax.swing.JPasswordField();
        pass2 = new javax.swing.JPasswordField();
        btnconf = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jrbencargado = new javax.swing.JRadioButton();
        jrbadmin = new javax.swing.JRadioButton();
        opa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de usuario:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 64, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cargo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmar contraseña:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 181, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 123, -1, -1));

        txtusuario.setBackground(new java.awt.Color(32, 32, 53));
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtusuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 86, 195, -1));

        pass1.setBackground(new java.awt.Color(32, 32, 53));
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        pass1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pass1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 145, 195, -1));

        pass2.setBackground(new java.awt.Color(32, 32, 53));
        pass2.setForeground(new java.awt.Color(255, 255, 255));
        pass2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pass2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 203, 195, -1));

        btnconf.setBackground(new java.awt.Color(0, 0, 0));
        btnconf.setForeground(new java.awt.Color(255, 255, 255));
        btnconf.setText("Confirmar");
        btnconf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfActionPerformed(evt);
            }
        });
        jPanel2.add(btnconf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 92, 33));

        btnsalir.setBackground(new java.awt.Color(0, 0, 0));
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Volver");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 92, 33));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear nuevo usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btg1.add(jrbencargado);
        jrbencargado.setForeground(new java.awt.Color(255, 255, 255));
        jrbencargado.setSelected(true);
        jrbencargado.setText("Encargado");
        jrbencargado.setOpaque(false);
        jrbencargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbencargadoActionPerformed(evt);
            }
        });
        jPanel2.add(jrbencargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        btg1.add(jrbadmin);
        jrbadmin.setForeground(new java.awt.Color(255, 255, 255));
        jrbadmin.setText("Aministrador");
        jrbadmin.setOpaque(false);
        jPanel2.add(jrbadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));
        jPanel2.add(opa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 350));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 300, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teslas-library-1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 417, 373));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        if(biblio.Login.rang.equals("0")){
         new MenuAdmin().setVisible(true);
         this.setVisible(false);
        }if(biblio.Login.rang.equals("1")){
            new MenuEncargado().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfActionPerformed
        // TODO add your handling code here:
        ver();
        verf();
        if(validar.equals("t")){
            try{
                hash();
                jrbrango();
                conn = DB.Mysql.getConnection();
                String sql = "insert into usuario (NOMBRE_USUARIO,CONTRASENIA_USUARIO,RANGO_USUARIO)"
                +"values('"+txtusuario.getText()+"',"
                +"'"+hashpass+"','"+jrb+"')";
                sent = conn.createStatement();
                int n = sent.executeUpdate(sql);
                if(n>0){
                    JOptionPane.showMessageDialog(null,"Usuario guardado");
                    new Login().setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null,"No se pudo crear el usuario");
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }else{
            //JOptionPane.showMessageDialog(null, "No se puede crear el usuario");
        }
    }//GEN-LAST:event_btnconfActionPerformed

    private void jrbencargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbencargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbencargadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg1;
    private javax.swing.JButton btnconf;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrbadmin;
    private javax.swing.JRadioButton jrbencargado;
    private javax.swing.JLabel opa;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
